name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: part11
    steps:
      - uses: actions/checkout@v6
      - name: Date
        run: |
          date
      - name: List files
        run: |
          ls -l
